[project]
name = "iMOD-Documentation"
version = "0.1.0"
authors = [
    "Joeri van Engelen <joerivanengelen@deltares.nl>",
    "Hofer-Julian <julianhofer@deltares.nl>",
]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]

[tasks]
install-pre-commit = "pre-commit install"
pre-commit = "pre-commit run --all-files"
jupyter = "jupyter lab"
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" }
quarto-check = { cmd = "quarto check all", depends_on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends_on = [
    "quartodoc-build",
] }
docs = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends_on = [
    "quartodoc-build",
] }

[dependencies]
modflow6 = ">=6.4.4"
imod = ">=0.16.0"
jupyterlab = "*"
pre-commit = "*"
primod = "*"
quarto = "*"
quartodoc = "*"
