[project]
name = "iMOD-Documentation"
version = "0.1.0"
authors = ["Joeri van Engelen <joerivanengelen@deltares.nl>", "Hofer-Julian <julianhofer@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]

[tasks]
install-pre-commit = "pre-commit install"
pre-commit = "pre-commit run --all-files"
jupyter = "jupyter lab"
quarto-check = "quarto check all"
quarto-render = "export QUARTO_PYTHON=python && quarto render docs --to html --execute"
docs = "export QUARTO_PYTHON=python && quarto preview docs"

[dependencies]
imod = "*"
jupyterlab = "*"
pre-commit = "*"
primod = "*"
quarto = "*"
