project:
  type: website
  output-dir: _build

website:
  title: "iMOD Suite Tutorial"
  navbar:
    left:
      - Tutorial-iMOD-Suite.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

  pdf:
    documentclass: scrreprt