project:
  output-dir: _build

profile:
  group: 
    - [website, manual, install, tutorial]


quartodoc:
  style: pkgdown
  dir: primod_api
  title: Primod API Reference
  package: primod
  sections:
    - title: MetaMod
      desc: Couple MetaSWAP and MODFLOW 6.
      contents:
        - MetaMod
        - MetaModDriverCoupling
    - title: RibaMod
      desc: Couple Ribasim and MODFLOW 6.
      contents:
        - RibaMod
        - RibaModActiveDriverCoupling       
        - RibaModPassiveDriverCoupling       
    - title: RibaMetaMod
      desc: Couple Ribasim, MetaSWAP and MODFLOW 6.
      contents:
        - RibaMetaMod
        - RibaMetaDriverCoupling
        - RibaModActiveDriverCoupling
        - RibaModPassiveDriverCoupling
        - MetaModDriverCoupling
