project:
  type: book

book:
  title: "iMOD Suite User Guide"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: viewer.qmd
      chapters:
        - viewer_install.qmd
        - viewer_install_msi.qmd
        - qgis_user_manual.qmd
        - 3dviewer_user_manual.qmd
        - viewer_known_issues.qmd
    - part: python.qmd
      chapters:
        - python_install.qmd
        - deltaforge_install.qmd
        - python_getting_started.qmd
    - part: coupler.qmd
      chapters:
        - coupler_metamod_config.qmd
        - coupler_metamod_technical.qmd
        - coupler_metamod_example.ipynb
        - coupler_ribamod_config.qmd
        - coupler_ribamod_technical.qmd
        - coupler_ribamod_preprocessing.qmd
        - primod_api/index.qmd
        - coupler_architecture.qmd
        - coupler_release.qmd
    - part: tutorial.qmd
      chapters:
        - tutorial_Abbeyfeale.qmd
        - tutorial_Dommel.qmd
        - tutorial_wq.qmd
        - tutorial_Hondsrug.ipynb

format:
  pdf:
    documentclass: scrreprt
    top-level-division: chapter
