---
title: Configuration
---

The configuration file is necessary to describe the model and its dependencies.
It is in the [toml](https://toml.io/en/) format and should have a `.toml`
extension.

Note that `toml` uses quote marks differently than `python`. Single quotes in
toml (`''`) are interpreted similarly to how python would interpret a rawstring
(`r''` or `r""`), whereas double quotes (`""`) are interpreted in a similar
manner to regular strings in python (`""` or `''`). This matters for paths on
Windows, for which we advice to use single quotes.

```toml
log_level = "INFO"
timing = false
driver_type = "ribamod"

[driver.kernels.modflow6]
dll = "./kernels/modflow6/libmf6.dll"
work_dir = "./mf6_data"

[driver.kernels.ribasim]
dll = "./kernels/ribasim/bin/libribasim.dll"
dll_dep_dir = "./kernels/ribasim/bin"
config_file = "./ribasim_data/ribasim.toml"

[[driver.coupling]]
mf6_model = "inner_model"
mf6_active_river_packages = {"riv_1" = "./mappings_inner/riv_1.tsv"}
mf6_passive_river_packages = {"riv_2" = "./mappings_inner/riv_2.tsv"}
mf6_active_drainage_packages = {"drn_1" = "./mappings_inner/drn_1.tsv"}
mf6_passive_drainage_packages = {}

[[driver.coupling]]
mf6_model = "outer_model"
mf6_active_river_packages = {"riv_3" = "./mappings_outer/riv_3.tsv"}
mf6_passive_river_packages = {"riv_4" = "./mappings_outer/riv_4.tsv", "riv_5" = "./mappings_outer/riv_5.tsv"}
mf6_active_drainage_packages = {}
mf6_passive_drainage_packages = {"drn_2" = "./mappings_outer/drn_2.tsv"}
```


## Config schema


|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | This setting determines the severity and therefore the verbosity of the log messages.                                |
| type          | str                                                                                                               |
| required      | false                                                                                                                |
| default       | INFO                                                                                                                 |
| enum          | DEBUG, INFO, WARNING, ERROR, CRITICAL                                                                                |
: log_level

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies whether the coupling should be timed. This option requires the log level to at least include INFO.         |
| type          | boolean                                                                                                              |
| required      | false                                                                                                                |
| default       | false                                                                                                                |
: timing

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies which driver should be used. Typically, this determines which hydrological kernels are coupled.            |
| type          | str                                                                                                               |
| required      | true                                                                                                                 |
| enum          | ribamod                                                                                                              |
: driver_type

### driver.kernels.modflow6

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the MODFLOW 6 library.                                                                                   |
| type          | str                                                                                                               |
| required      | true                                                                                                                 |
: dll

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the dependencies of MODFLOW 6.                                                                           |
| type          | str                                                                                                               |
| required      | false                                                                                                                |
: dll_dep_dir

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The working directory MODFLOW 6 expects. This is the directory where the simulation name file resides.               |
| type          | str                                                                                                               |
| required      | true                                                                                                                 |
: work_dir

### driver.kernels.ribasim

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the Ribasim library.                                                                                     |
| type          | str                                                                                                               |
| required      | true                                                                                                                 |
: dll

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the dependencies of Ribasim.                                                                             |
| type          | str                                                                                                               |
| required      | true                                                                                                                |
: dll_dep_dir

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the Ribasim config file.                                                                                 |
| type          | str                                                                                                               |
| required      | true                                                                                                                 |
: config_file

### driver.coupling


|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the MODFLOW 6 model name to which Ribasim will be coupled.                                                 |
| type          | str                                                                                                               |
| required      | true                                                                                                                 |
: mf6_model

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the active river packages of MODFLOW 6 that will be coupled together with the path to the mapping table.   |
| type          | dict[str, str]                                                                                                       |
| required      | true                                                                                                                 |
: mf6_active_river_packages

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the passive river packages of MODFLOW 6 that will be coupled together with the path to the mapping table.  |
| type          | dict[str, str]                                                                                                       |
| required      | true                                                                                                                 |
: mf6_passive_river_packages

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the active drainage packages of MODFLOW 6 that will be coupled together with the path to the mapping table.|
| type          | dict[str, str]                                                                                                       |
| required      | true                                                                                                                 |
: mf6_active_drainage_packages

|               |                                                                                                                       |
|---------------|-----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the passive drainage packages of MODFLOW 6 that will be coupled together with the path to the mapping table.|
| type          | dict[str, str]                                                                                                        |
| required      | true                                                                                                                  |
: mf6_passive_drainage_packages