---
title: Configuration
---

The configuration file is necessary to describe the model and its dependencies.
It is in the [toml](https://toml.io/en/) format and should have a `.toml`
extension.

Note that `toml` uses quote marks differently than `python`. Single quotes in toml (`''`) are interpreted similarly to how python would interpret a rawstring (`r''` or `r""`), whereas double quotes (`""`) are interpreted in a similar manner to regular strings in python (`""` or `''`). This matters for paths on Windows, for which we advice to use single quotes.

```toml
log_level = 'INFO'
timing = false
driver_type = 'metamod'

# MODFLOW 6
[driver.kernels.modflow6]
dll = './kernels/libmf6.dll'
work_dir = './mf6_data'

# MetaSWAP
[driver.kernels.metaswap]
dll = './kernels/MetaSWAP.dll'
dll_dep_dir = './kernels/3rdparty'
work_dir = './msw_data'

# Inner model with sprinkling
[[driver.coupling]]
enable_sprinkling = true
mf6_model = 'inner_model'
mf6_msw_recharge_pkg = 'RCH_MSW'
mf6_msw_well_pkg = 'WELLS_MSW'
mf6_msw_node_map = 'mappings_inner/nodenr2svat.dxc'
mf6_msw_recharge_map = 'mappings_inner/rchindex2svat.dxc'
mf6_msw_sprinkling_map = 'mappings_inner/wellindex2svat.dxc'

# Outer model, without sprinkling
[[driver.coupling]]
enable_sprinkling = false
mf6_model = 'outer_model'
mf6_msw_recharge_pkg = 'RCH_MSW'
mf6_msw_node_map = 'mappings_outer/nodenr2svat.dxc'
mf6_msw_recharge_map = 'mappings_outer/rchindex2svat.dxc'
```


## Config schema


|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | This setting determines the severity and therefore the verbosity of the log messages.                                 |
| type          | string                                                                                                               |
| required      | false                                                                                                                |
| default       | INFO                                                                                                                 |
| enum          | DEBUG, INFO, WARNING, ERROR, CRITICAL                                                                                 |
: log_level

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies whether the coupling should be timed. This option requires the log level to at least include INFO.          |
| type          | boolean                                                                                                              |
| required      | false                                                                                                                |
| default       | false                                                                                                                |
: timing

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies which driver should be used. Typically, this determines which hydrological kernels are coupled.            |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
| enum          | metamod                                                                                                              |
: driver_type

### driver.kernels.modflow6

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the MODFLOW 6 library.                                                                                   |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: dll

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the dependencies of MODFLOW 6.                                                                            |
| type          | string                                                                                                               |
| required      | false                                                                                                                |
: dll_dep_dir

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The working directory MODFLOW 6 expects. This is the directory where the simulation name file resides.               |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: work_dir

### driver.kernels.metaswap

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the MetaSWAP library.                                                                                     |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: dll

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The path to the dependencies of MetaSWAP.                                                                              |
| type          | string                                                                                                               |
| required      | false                                                                                                                |
: dll_dep_dir

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | The working directory MetaSWAP expects.                                                                                |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: work_dir

### driver.coupling

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Whether to enable sprinkling, that is: enable extracting groundwater for irrigation.                                   |
| type          | boolean                                                                                                              |
| required      | true                                                                                                                 |
: enable_sprinkling

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the MODFLOW 6 model name to which MetaSWAP will be coupled.                                                  |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: mf6_model

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the package name (specified in the Modflow 6 simulation name file) of the recharge package to which MetaSWAP will be coupled. |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: mf6_msw_recharge_pkg

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Specifies the package name (specified in the Modflow 6 simulation name file) of the recharge package to which MetaSWAP will be coupled. This setting is only required if `enable_sprinkling` is set to `true`. |
| type          | string                                                                                                               |
| required      | false                                                                                                                |
: mf6_msw_well_pkg

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Path to the file specifying the mapping between MODFLOW 6 cells and MetaSWAP svats.                                   |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: mf6_msw_node_map

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Path to the file specifying the mapping between MODFLOW 6 recharge cells and MetaSWAP svats.                          |
| type          | string                                                                                                               |
| required      | true                                                                                                                 |
: mf6_msw_recharge_pkg

|               |                                                                                                                      |
|---------------|----------------------------------------------------------------------------------------------------------------------|
| description   | Path to the file specifying the mapping between MODFLOW 6 wells and MetaSWAP svats. This setting is only required if `enable_sprinkling` is set to `true`. |
| type          | string                                                                                                               |
| required      | false                                                                                                                |
: mf6_msw_sprinkling_map