---
title: Further Links
---

## Description

This part points you to more information about iMOD.

## Videos

A list of videos which are iMOD Suite related are shown below. Note that due to
privacy seetings, you might need follow the link below the video to view it on
the Deltares Vimeo page.

```{=html}
<iframe src="https://player.vimeo.com/video/651111537?h=53d277cee4" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/651111537">iMOD User Day 2021</a> from <a href="https://vimeo.com/deltares">Deltares</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

## Practical Tips

We also maintain documentation with general practical and technical
tips. It varies from fixing specific Powershell errors to a full
explanation on how to do proper version control of both your data and
scripts with Git and DVC.

[iMOD Practical
tips](https://deltares.gitlab.io/imod/imod-practical-tips/)

## Source Code

Below is the list of repositories that contain the source code of the
individual components. You can raise issues, or suggest changes, here.

-   [iMOD Documentation
    Github](https://github.com/Deltares/iMOD-Documentation)
-   [iMOD QGIS plugin Github](https://github.com/Deltares/imod-qgis)
-   [iMOD 3D Viewer Github](https://github.com/Deltares/imod-gui)
-   [iMOD Python Gitlab](https://gitlab.com/deltares/imod/imod-python)
