---
title: "{{< fa brands python >}} iMOD Python"
image: figures/logo/iMOD-python.svg
description: 'Build large groundwater models with scripts'
index: "3"
---

The iMOD Python package is designed to help you in your MODFLOW
groundwater modeling efforts. It makes it easy to go from your raw data
to a fully defined MODFLOW model, with the aim to make this process
reproducible. Whether you want to build a simple 2D conceptual model, or
a complex 3D regional model with millions of cells, iMOD Python scales
automatically by making use of [dask](https://dask.org/).

By building on top of popular Python packages like
[xarray](http://xarray.pydata.org/),
[pandas](http://pandas.pydata.org/),
[rasterio](https://rasterio.readthedocs.io/en/latest/) and
[geopandas](http://geopandas.org/), a lot of functionality comes for
free.

Currently we support the creation of the following MODFLOW-based models:

-   [USGS MODFLOW
    6](https://www.usgs.gov/software/modflow-6-usgs-modular-hydrologic-model),
    currently only the Groundwater Flow packages
-   [iMODFLOW](https://oss.deltares.nl/web/imod)
-   [iMOD-WQ](https://oss.deltares.nl/web/imod), which integrates SEAWAT
    (density-dependent groundwater flow) and MT3DMS (multi-species
    reactive transport calculations)

Documentation: <https://deltares.gitlab.io/imod/imod-python> This
documentation includes a section \"How do I\" which can be used for
common data conversions in imod-python or xarray. This section will be
regular updated based on the different questions of users.

Source code: <https://gitlab.com/deltares/imod/imod-python>
