# Based on: https://tarleb.com/posts/quarto-with-gh-pages/
name: Publish Website

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: ['main']
  pull_request:


jobs:
  quarto-html:
    name: Publish with Quarto
    runs-on: ubuntu-latest
    steps:
        # Circumvent this problem: https://github.com/actions/checkout/issues/165
      - name: Checkout code with LFS cache
        uses: nschloe/action-checkout-with-lfs-cache@v1

      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          pixi-version: "latest"
      - name: Prepare pixi
        run: pixi run install-without-pre-commit

      - name: Check Quarto installation and all engines
        run: pixi run quarto-check

      - name: Render Quarto Project
        run: pixi run quarto-render

      - name: Publish Quarto Project
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  quarto-pdf:
    name: Publish with Quarto
    runs-on: ubuntu-latest
    steps:
        # Circumvent this problem: https://github.com/actions/checkout/issues/165
      - name: Checkout code with LFS cache
        uses: nschloe/action-checkout-with-lfs-cache@v1

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTex
        run: quarto install tinytex

      - name: Render Manual
        run: "quarto render docs --profile manual --to pdf"

      - name: Render Tutorial
        # --no-clean to skip cleanup before rendering
        run: "quarto render docs --no-clean --profile tutorial --to pdf"

      - name: Render Installation Guide
        # --no-clean to skip cleanup before rendering
        run: "quarto render docs --no-clean --profile install --to pdf"

      - name: Upload artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: iMOD-Suite-Guides
          path: |
            docs/_build/iMOD-Suite-User-Guide.pdf
            docs/_build/iMOD-Suite-Tutorial.pdf
            docs/_build/iMOD-Suite-Installation-Guide.pdf
