# Based on: https://tarleb.com/posts/quarto-with-gh-pages/
name: Publish Website

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches: [main, update/pixi-lock]
    tags: ["*"]
  pull_request:


jobs:
  quarto-html:
    name: HTML
    runs-on: ubuntu-latest
    steps:
        # Circumvent this problem: https://github.com/actions/checkout/issues/165
      - name: Checkout code with LFS cache
        uses: nschloe/action-checkout-with-lfs-cache@v1

      - uses: prefix-dev/setup-pixi@v0.5.2
        with:
          pixi-version: "latest"

      - name: Check Quarto installation and all engines
        run: pixi run quarto-check

      - name: Render Quarto Project
        run: pixi run quarto-render

      - name: Publish Quarto Project
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
