name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
# Circumvent this problem: https://github.com/actions/checkout/issues/165
      - name: Checkout code with LFS cache
        uses: nschloe/action-checkout-with-lfs-cache@v1

      - name: Build HTML with tox
        run: |
          pip install tox
          tox -e build

      - name: Deploy HTML to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .tox/docs_out

      - name: Build latex with tox
        run: |
          tox -e build_latex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: imod-doc.tex
          working_directory: .tox/docs_latex
          args: -pdf -dvi- -ps-
          latexmk_use_xelatex: true
        
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: .tox/docs_latex/imod-doc.pdf